version: '3.1'
services: 
  post:
    image: postgres:10-alpine
    ports:
      - "5436:5432"
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  admin:
    image: adminer
    restart: always
    links: 
      - post:db
    ports: 
      - 8082:8080
